[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib', 'node_modules']
test = 'forge-test'
script = 'scripts'
optimizer_runs = 10
via-ir = true
build_info = true
extra_output = ['storageLayout']
fs_permissions = [{ access = "read-write", path = "./"}]

[rpc_endpoints]
ethereum ="${RPC_ETHEREUM_MAINNET}"
optimism = "${RPC_OPTIMISM_MAINNET}"
polygon = "${RPC_POLYGON_MUMBAI}"
arbitrum = "${RPC_ARBITRUM_MAINNET}"
base = "${RPC_BASE_MAINNET}"
arbitrum_sepolia = "${RPC_ARBITRUM_SEPOLIA}"
ethereum_sepolia ="${RPC_ETHEREUM_SEPOLIA}"
optimism_sepolia = "${RPC_OPTIMISM_SEPOLIA}"
polygon_mumbai = "${RPC_POLYGON_MUMBAI}"
base_sepolia = "${RPC_BASE_SEPOLIA}"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
